### ISSUE TITLE
视频类文件如何下载

### ISSUE THREAD

**Issue by wjykim** [yangkghjh/shimo#2]
麻烦问下如果石墨文件夹里放的是mp4文件，应该如何下载？

**Comment by yangkghjh** [comment]
石墨不支持视频吧

**Comment by wjykim** [comment]
> 石墨不支持视频吧

感谢回复~问题已经解决了。石墨是可以存放视频的（虽然我也不知道怎么存的，但是业务方交付视频是通过石墨的文件夹）。具体解决思路就是解析json数据中的'downloadUrl'字段，然后用这个url通过带cookie的方式get请求就可以下载到了~感觉通过这种方式其他石墨文档中不常见类型的文件也可以爬取

**Comment by wjykim** [comment]
感谢回复问题已经解决了。石墨是可以存放视频的（虽然我也不知道怎么存的，但是业务方交付视频是通过石墨的文件夹）。具体解决思路就是解析json数据中的'downloadUrl'字段，然后用这个url通过带cookie的方式get请求就可以下载到了感觉通过这种方式其他石墨文档中不常见类型的文件也可以爬取
