### ISSUE TITLE
避免重复下载

### ISSUE THREAD

**Issue by ZERO4OREZ** [yangkghjh/shimo#6]
感谢作者，亲测有效。但是如果我后边又新建了文档，想下载下来，但不想重复下载之前下载过的文档，可以怎么处理呢？

我自己的想法是在下载队列中判断这个文档最后的更新时间，但是这个接口具体是啥呀？找了半天石墨文档的 api 等信息都没找到对应的东西。

希望大佬帮忙看看。

**Comment by yangkghjh** [comment]
在 getFileList 方法里获取的文件列表是有更新事件的，字段是 `updatedAt`。

**Comment by ZERO4OREZ** [comment]
> 在 getFileList 方法里获取的文件列表是有更新事件的，字段是 `updatedAt`。

感谢，用这个字段解决了问题。https://github.com/yangkghjh/shimo/pull/8#issue-1031336682
